const express = require("express");
const fs = require("fs");
const { logApplication } = require("./log_applications");
const app = express();

app.use(express.json());

const PORT = 5000;

// Helper to get jobs
const getJobs = () => JSON.parse(fs.readFileSync("./jobs.json", "utf8"));

// In-memory DB for the demo
let applications = [];

/**
 * 1. SEARCH JOBS
 */
app.get("/api/jobs", (req, res) => {
  const start = parseInt(req.query.start) || 0;
  const limit = Math.min(parseInt(req.query.limit) || 5, 5); 
  console.log(
    `[JOB LIST] Fetching jobs from offset ${start} with limit ${limit}`,
  );
  const jobs = getJobs();
  res.json({
    jobs: jobs.slice(start, start + limit),
    next_offset: start + limit < jobs.length ? start + limit : null,
  });
});

/**
 * 2. AUTO-APPLY (Realistic Submission)
 */
app.post("/api/apply", (req, res) => {
  const {
    jobId,
    fullName, // Added: Essential for any portal
    studentEmail,
    workAuthStatus, // Added: To check "Safety Constraints"
    tailoredResume, // The "Variant" generated by LLM
    recruiterNote, // The personalized blurb
    evidenceMap, // The "Reasoning" (Requirement -> Bullet Point)
  } = req.body;

  console.log(`[APPLICATION RECEIVED] ${fullName} is applying to Job ID: ${jobId}`);
  
  // 🔴 LOG RAW APPLICATION DATA (before validation)
  logApplication({
    source: "api/apply",
    ip: req.ip,
    headers: {
      userAgent: req.headers["user-agent"],
    },
    body: req.body,
  });


  // Validation: Ensure the Agent isn't skipping steps
  const requiredFields = [
    "jobId",
    "fullName",
    "studentEmail",
    "tailoredResume",
    "evidenceMap",
  ];
  const missing = requiredFields.filter((field) => !req.body[field]);

  if (missing.length > 0) {
    return res.status(422).json({
      error: "Incomplete Application",
      missing_fields: missing,
    });
  }

  // Logic: Cross-reference with the Job Database
  const jobs = getJobs();
  const job = jobs.find((j) => j.id === jobId);

  if (!job) return res.status(404).json({ error: "Job not found" });

  // PERSONALIZATION CHECK:
  // Does the evidenceMap cover the job's required skills?
  // const jobSkills = job.required_skills || [];
  // const providedSkills = evidenceMap.map((e) => e.requirement.toLowerCase());

  // const missingEvidence = jobSkills.filter(
  //   (skill) =>
  //     !providedSkills.some((provided) =>
  //       provided.includes(skill.toLowerCase()),
  //     ),
  // );

  // if (missingEvidence.length > 0) {
  //   return res.status(400).json({
  //     error: "Grounding Error",
  //     message:
  //       "The AI failed to map your experience to these requirements: " +
  //       missingEvidence.join(", "),
  //   });
  // }

  // Store the application
  const newApp = {
    appId: `DB-${Math.random().toString(36).toUpperCase().substring(7)}`,
    fullName,
    jobId,
    studentEmail,
    workAuthStatus, // Added: To check "Safety Constraints"
    tailoredResume, // The "Variant" generated by LLM
    recruiterNote, // The personalized blurb
    evidenceMap, // The "Reasoning" (Requirement -> Bullet Point)
    status: "Applied",
    submittedAt: new Date().toISOString(),
  };
  applications.push(newApp);

  //   🟢 LOG FINAL STORED APPLICATION
  logApplication({
    source: "application_saved",
    appId: newApp["appId"],
    jobId: jobId,
    fullName: fullName,
    status: newApp["status"],
  });

  console.log(
    `[SUBMISSION] ${fullName} applied to ${job.company} for ${job.title}`,
  );
  res.status(201).json({ success: true, receipt: newApp });
});

/**
 * 3. Status Check
 */
app.get("/api/application-status", (req, res) => {
  const { email, jobId } = req.query;
  const found = applications.find(
    (a) => a.jobId === jobId && a.email === email,
  );

  console.log(
    `[STATUS CHECK] Application status requested for ${email} on Job ID ${jobId}`,
  );
  res.json({
    applied: !!found,
    status: found ? "Under Review" : "Not Found",
    record: found || null,
  });
});

app.listen(PORT, () => {
  console.log(`🚀 Realistic Sandbox Portal online at http://localhost:${PORT}`);
});
